name: Analyse de sécurité DevSecOps
on: [push]

jobs:
  analyse_de_securite:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Scanner les fichiers de configuration (IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config' # On scanne le fichier Dockerfile, pas une image
          format: 'table'
          exit-code: '0' # On force le passage au vert pour l'instant
          severity: 'CRITICAL,HIGH'
